# Use Python base image  
FROM python:3.9  

# Set working directory  
WORKDIR /app  

# Copy all files to container  
COPY . /app  

# Install dependencies  
RUN pip install --no-cache-dir -r requirements.txt  

# Run PyTest  
CMD ["pytest", "--junitxml=pytest-report.xml"]